stages:
  - secret-detection
  - test
  - post-test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/SAST-IaC.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'
  TRIVY_CACHE_DIR: .trivycache

sast:
  stage: test

secret_detection:
  stage: secret-detection

trivy-iac:
  stage: test
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  cache:
    key: trivy-cache
    paths:
      - .trivycache/
  script:
    - trivy --version
    - trivy config --format json --output trivy-iac-report.json .
    - trivy config --format table --exit-code 1 .
  artifacts:
    when: always
    paths:
      - trivy-iac-report.json
    expire_in: 1 week


parse-sast-results:
  stage: post-test
  image: alpine:latest
  before_script:
    - apk add --no-cache jq
  script:
    - echo "=== SECRET DETECTION RESULTS ==="
    - |
      if [ -f "gl-secret-detection-report.json" ]; then
        jq -r '.vulnerabilities[] | "Severity: [\(.severity)] | Category: \(.category) \nDescription: \(.message) \nLocation: \(.location.file):\(.location.start_line)\n-----------------------------------"' gl-sast-report.json
      else
        echo "gl-secret-detection-report.json not found."
      fi
    - echo "=== SAST RESULTS ==="
    - |
      if [ -f "gl-sast-report.json" ]; then
        jq -r '.vulnerabilities[] | "Severity: [\(.severity)] | Category: \(.category) \nDescription: \(.message) \nLocation: \(.location.file):\(.location.start_line)\n-----------------------------------"' gl-sast-report.json
      else
        echo "gl-sast-report.json not found."
      fi
