stages:
  - secret-detection
  - test
  - post-test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/SAST-IaC.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'

sast:
  stage: test

secret_detection:
  stage: secret-detection


parse-sast-results:
  stage: post-test
  image: alpine:latest
  before_script:
    - apk add --no-cache jq
  script:
    - echo "=== SECRET DETECTION RESULTS ==="
    - |
      if [ -f "gl-secret-detection-report.json" ]; then
        jq -r '.vulnerabilities[] | "Severity: [\(.severity)] | Category: \(.category) \nDescription: \(.message) \nLocation: \(.location.file):\(.location.start_line)\n-----------------------------------"' gl-sast-report.json
      else
        echo "gl-secret-detection-report.json not found."
      fi
    - echo "=== SAST RESULTS ==="
    - |
      if [ -f "gl-sast-report.json" ]; then
        jq -r '.vulnerabilities[] | "Severity: [\(.severity)] | Category: \(.category) \nDescription: \(.message) \nLocation: \(.location.file):\(.location.start_line)\n-----------------------------------"' gl-sast-report.json
      else
        echo "gl-sast-report.json not found."
      fi