#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/decrypt-private-files.sh

Decrypts every SOPS/age-encrypted *.sops file linked in from the private
secrets repo into its plaintext counterpart next to it, for each Terraform
project root (infra/, authentik/): terraform.tfvars.sops becomes
terraform.tfvars, backend.hcl.sops becomes backend.hcl. Each is a whole-file
binary encryption, since neither format is YAML/JSON. The plaintext files are
gitignored and regenerated by this script - never edit them directly, and
never commit them. Missing *.sops files (not every checkout links all of
them) are skipped.

Requires sops, and either the personal age private key at
~/.config/sops/age/keys.txt or SOPS_AGE_KEY[_FILE] set (CI uses the latter).

To edit a secret itself:
  sops edit --input-type binary --output-type binary infra/terraform.tfvars.sops
  scripts/decrypt-private-files.sh
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
repo_root="$(cd -- "$script_dir/.." && pwd -P)"
cd "$repo_root"

sops_files=(
  "infra/terraform.tfvars.sops"
  "infra/backend.hcl.sops"
  "authentik/terraform.tfvars.sops"
  "authentik/backend.hcl.sops"
)

found=0
for sops_file in "${sops_files[@]}"; do
  if [[ ! -e "$sops_file" ]]; then
    echo "Skipping (not linked): $sops_file" >&2
    continue
  fi

  plain_file="${sops_file%.sops}"
  # Decrypt to a temporary file first. Redirecting straight into $plain_file
  # truncates it before sops runs, so a failed decrypt (missing age key, for
  # one) would destroy a working plaintext file.
  tmp_file="$(mktemp -- "${plain_file}.XXXXXX")"
  chmod 600 -- "$tmp_file"
  if ! sops decrypt --input-type binary --output-type binary -- "$sops_file" > "$tmp_file"; then
    rm -f -- "$tmp_file"
    echo "ERROR: failed to decrypt $sops_file; left $plain_file untouched." >&2
    exit 1
  fi
  mv -- "$tmp_file" "$plain_file"
  chmod 600 -- "$plain_file"
  echo "Decrypted $sops_file -> $plain_file"
  found=$((found + 1))
done

if ((found == 0)); then
  echo "ERROR: no *.sops files found. Run scripts/link-private-files.sh first." >&2
  exit 1
fi
